name: Build restic binary manually
description: |
  Build manually, because until some point Dockerfile did not build the binary itself, but was provided pre-built binary.
  This was a made a separate composite action because otherwise a bunch of `if`s with same condition would have been required for each `step`.

inputs:
  workdir:
    description: Working directory for restic
    required: false
    default: .
  semver-broken:
    description: Whether or not semver check in current version is broken, e.g. `1.10.0` > `1.9.0` returns `false`
    required: true

runs:
  using: composite
  steps:
    - name: Check if `go.mod` exists
      id: go-mod
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        if [[ -e $WORKDIR/go.mod ]]; then EXISTS=true; else EXISTS=false; fi
        HAS_VERSION=false
        if [[ $EXISTS == 'true' ]]; then
          FOUND=$(grep '^go [[:digit:]]\.[[:digit:]]\+' $WORKDIR/go.mod -c || :)
          if [[ $FOUND -gt 0 ]]; then HAS_VERSION=true; else HAS_VERSION=false; fi
        fi
        echo has-version=$HAS_VERSION >> $GITHUB_OUTPUT
    - if: steps.go-mod.outputs.has-version == 'true'
      name: Set up go version from `go.mod`
      uses: actions/setup-go@v3
      env:
        WORKDIR: ${{ inputs.workdir }}
      with:
        go-version-file: ${{ env.WORKDIR }}/go.mod
    - if: steps.go-mod.outputs.has-version == 'false'
      name: Set up go version manually
      uses: actions/setup-go@v3
      with:
        # <1.10 because semver parsing was broken and 1.10.0 > 1.9.0 check failed
        # <=1.11.1 because go version in go.mod was provided first at v0.9.6, and v0.9.5 used go 1.11.1
        # See https://restic.readthedocs.io/en/v0.9.5/developer_information.html#reproducible-builds
        go-version: ${{ inputs.semver-broken == 'true' && '<1.10.0' || '<=1.11.1' }}
    - name: Manually build binary
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        cd $WORKDIR
        go run build.go --goos linux --goarch arm64