name: Build tags

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      push-image:
        required: false
        type: boolean
        default: false
    secrets:
      dockerhub-username:
        required: false
      dockerhub-token:
        required: false

jobs:
  build-tags:
    if: inputs.tags != '[]' && inputs.tags != ''
    uses: wooseopkim/publish-tags/.github/workflows/workflow.yml@v1
    with:
      tags: ${{ inputs.tags }}
      github-repository: restic/restic
      dockerhub-repository: wooseopkim/restic
      post-build-script: |
        ~/artifacts/scripts/verify_image $IMAGE $TAG
      push-image: ${{ inputs.push-image }}
      platforms: linux/arm64
      dockerfile: docker/Dockerfile
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}