name: Detect tags and build Docker images

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
    # The official docs: "The schedule event can be delayed during periods of high loads of
    # GitHub Actions workflow runs. High load times include the start of every hour. To decrease
    # the chance of delay, schedule your workflow to run at a different time of the hour."
    # 42 is for https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy
    # 9 is just a magic number
    - cron: '42 9 * * *'

env:
  GH_REPOSITORY: restic/restic
  DOCKERHUB_REPOSITORY: ${{ github.actor }}/restic
  PUSH_IMAGE: ${{ github.event_name == 'schedule' }}

concurrency:
  group: ${{ github.repository }}/${{ github.workflow }}/${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-images:
    strategy:
      matrix:
        include:
          - github-repository: restic/restic
            dockerhub-repository: wooseopkim/restic
            dockerfile: docker/Dockerfile
            platforms: linux/arm64
            first-tag: v0.13.0
            post-build-script: ./restic-arm64/verify $IMAGE $TAG
          - github-repository: etesync/server
            dockerhub-repository: wooseopkim/etesync
            pre-build-script: |
              mkdir -p $CHECKOUT_PATH/unofficial
              cp ./etesync-server/Dockerfile $CHECKOUT_PATH/unofficial/Dockerfile
            first-tag: v0.10.0
            dockerfile: unofficial/Dockerfile
            platforms: linux/amd64,linux/arm64
            post-build-script: ./etesync-server/verify $IMAGE $TAG
    uses: ./.github/workflows/build-image.yml
    with:
      github-repository: ${{ matrix.github-repository }}
      dockerhub-repository: ${{ matrix.dockerhub-repository }}
      dockerfile: ${{ matrix.dockerfile }}
      platforms: ${{ matrix.platforms }}
      first-tag: ${{ matrix.first-tag }}
      push-image: ${{ github.event_name == 'schedule' }}
      pre-build-script: ${{ matrix.pre-build-script }}
      post-build-script: ${{ matrix.post-build-script }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
